### ISSUE TITLE
emerge fails with "Invalid or corrupt dependency specification"

### ISSUE THREAD

**Issue by ghost** [MarcT/mt-mythtv#1]
I am using portage-2.2_rc49 and I get this error when I attempt an emerge:

emerge -av =media-tv/mythtv-9999

These are the packages that would be merged, in order:

Calculating dependencies \

!!! Invalid or corrupt dependency specification:

invalid atom: 'x11-libs/qt-core:4[qt3support]'

('ebuild', '/', 'media-tv/mythtv-9999', 'merge')

> =media-libs/freetype-2.0 >=media-sound/lame-3.93.1 x11-libs/libX11 x11-libs/libXext x11-libs/libXinerama x11-libs/libXv x11-libs/libXrandr x11-libs/libXxf86vm x11-libs/qt-core:4[qt3support] x11-libs/qt-gui:4[qt3support,tiff?] x11-libs/qt-sql:4[qt3support,mysql] x11-libs/qt-opengl:4[qt3support] x11-libs/qt-webkit:4 >=media-libs/alsa-lib-0.9 media-libs/libdvb media-tv/linuxtv-dvb-headers media-libs/libdvdcss media-sound/jack-audio-connection-kit app-misc/lirc dev-perl/DBD-mysql x11-proto/xineramaproto x11-proto/xf86vidmodeproto x11-apps/xinit dev-util/subversion net-misc/rsync

This package can not be installed. Please notify the 'media-
tv/mythtv-9999' package maintainer about this problem.  
 ... done!

**Comment by MarcT** [comment]
Works with portage-2.2_rc33.
I checked the official ebuild's dependencies for qt and updated to match.
See if that resolves it.

**Comment by ghost** [comment]
It turns out what it needed was an 'EAPI="2"' statement at the beginning. Once I did that, it accepted the build. It still doesn't build though. Now I'm getting a configure error about '--build' not being a valid configuration option.

**Comment by MarcT** [comment]
that would indicate an issue with the configure script for mythtv??? weird works fine here still.
I added EAPI-2 to all ebuild files, resync and that should resolve the original issue.
