### ISSUE TITLE
Mythtv needs --enable-x11

### ISSUE THREAD

**Issue by exelnet** [MarcT/mt-mythtv#10]
So it would be wise to add +X to the IUSE flags.

greetings

Jan Marc

**Comment by MarcT** [comment]
Again, I'm confused by an issue someone creates.
X is already in the IUSE for mythtv for all versions.

**Comment by exelnet** [comment]
When you read it as "+X" it does make sense doesn't it?

**Comment by MarcT** [comment]
X is not a requirement. MythTV has X as being optional so why would I force a user to use it? Besides, if you are using X, then your use flags should have X in them already.

**Comment by exelnet** [comment]
Ok maybe I should have gone into detail in the first place. 
It's all about the --disable-x11 useflag mythtv provides. This useflag is invalid if used on a linux system. There isn't any special error message, the build just fails somewhere in the middle. After speaking to the mythtv devs they told me on irc that users should not use this useflag on linux systems. If a user now doesn't use the X USE flag his build will fail since the --disable-x11 option is set by the ebuild.

To fix this you could either use +X as requirement or remove the --disable-x11 stuff from the configure phase.

The mythtv devs wont fix this issue since the flag is valid on non linux systems. And they even refused to implement a check. ;/

If you wanna try it out just build your ebuild without the X flag.

greetings

Jan Marc

**Comment by MarcT** [comment]
There you go.
