### ISSUE TITLE
problems building mythzoneminder

### ISSUE THREAD

**Issue by simonckenyon** [MarcT/mt-mythtv#11]
if i try i get:

!!! One of the following masked packages is required to complete your request:
- media-plugins/mythzoneminder-9999 (masked by: ~amd64 keyword, invalid: DEPEND: USE flag 'minimal' referenced in conditional 'minimal?' is not in IUSE, invalid: RDEPEND: USE flag 'minimal' referenced in conditional 'minimal?' is not in IUSE)

**Comment by MarcT** [comment]
minimal iuse flag has been fixed
As for the masked by ~amd64 you will have to add it to keywords.
