### ISSUE TITLE
0.24-fixes cannot build

### ISSUE THREAD

**Issue by glemsom** [MarcT/mt-mythtv#14]
System: AT5IONT-I (Atom), x86_64, gcc 4.5
CFLAGS: "-O2 -pipe"

When trying to build MythTV using this overlay (and using the 0.24-fixes branch), emerge just bailes out with:

make[2]: Leaving directory `/var/tmp/portage/media-tv/mythtv-9999/work/mythtv/programs/mythfrontend'
make[1]: Leaving directory`/var/tmp/portage/media-tv/mythtv-9999/work/mythtv/programs'
make: **\* [programs] Error 2
emake failed
- ERROR: media-tv/mythtv-9999 failed:
-   (no error message)
- 
- Call stack:
-     ebuild.sh, line   56:  Called src_compile
-   environment, line 3694:  Called myth-git_src_compile
-   environment, line 3150:  Called die
- The specific snippet of code:
-       emake CC="$(tc-getCC)" CXX="$(tc-getCXX)" "${@}" || die
- 
- If you need support, post the output of 'emerge --info =media-tv/mythtv-9999',
- the complete build log and the output of 'emerge -pqv =media-tv/mythtv-9999'.
- This ebuild used the following eclasses from overlays:
-   /var/lib/layman/mt-mythtv/eclass/myth-git.eclass
- This ebuild is from an overlay named 'MythTV-0.24-fixes': '/var/lib/layman/mt-mythtv/'
- The complete build log is located at '/var/tmp/portage/media-tv/mythtv-9999/temp/build.log'.
- The ebuild environment file is located at '/var/tmp/portage/media-tv/mythtv-9999/temp/environment'.
- S: '/var/tmp/portage/media-tv/mythtv-9999/work'
  localhost ~ # make[2]: Leaving directory `/var/tmp/portage/media-tv/mythtv-9999/work/mythtv/programs/mythfrontend'

**Comment by MarcT** [comment]
Trunk build test, success.
0.24-fixes build test, success.

Please provide the following info:
The output of ebuild --info
The config options for your myth build.
The complete build log from the failed build, if you have to find another location to store it that is fine.

**Comment by glemsom** [comment]
I found the error.
For some odd reason, the snapshot of MythTV was not complete.

So, my workaround was to delete /usr/portage/distfiles/git-src/mythtv, and let the MythTV ebuild re-download the snapshot.
After that, MythTV builds just fine! :)
