### ISSUE TITLE
mythvideo depends on sys-apps/eject, which doesn't Exist anymore

### ISSUE THREAD

**Issue by cctsurf** [MarcT/mt-mythtv#15]
The title says most of it, I really appreciate your labors on this. Today, I was updating my system and it moved me back to mythtv-0.23.  In researching why, I noted this dependency seems to have disappeared from gentoo portage (I think it moved to sys-block/eject).  Thanks again!
cctsurf

**Comment by drescherjm** [comment]
I will try to take a look at this over the weekend. It may be difficult for me since I switched to 0.24 this week. And I know Marc is using either 0.24 or the trunk.

**Comment by cctsurf** [comment]
Thanks, I've been using 0.24 trunk using your ebuilds, but because of the dependency, portage moved me back to 0.23_something.  That's why I posted, sorry for the confusion. thanks again
cctsurf

**Comment by drescherjm** [comment]
I see sys-apps/eject was Moved to sys-block/eject 29 hours ago..

http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/sys-apps/eject/?hideattic=0

I will fix this when I get home if Marc does not..

**Comment by MarcT** [comment]
I fixed this in trunk and 0.24-fixes. If someone comments we need this on 0.23-fixes I'll do it there too.
