### ISSUE TITLE
mythtv-status seems to need dev-perl/Sys-SigAction

### ISSUE THREAD

**Issue by drescherjm** [MarcT/mt-mythtv#17]
jmd0 ~ # mythtv-status
Can't locate Sys/SigAction.pm in @INC (@INC contains: /etc/perl /usr/lib64/perl5/site_perl/5.12.4/x86_64-linux /usr/lib64/perl5/site_perl/5.12.4 /usr/lib64/perl5/vendor_perl/5.12.4/x86_64-linux /usr/lib64/perl5/vendor_perl/5.12.4 /usr/lib64/perl5/site_perl /usr/lib64/perl5/vendor_perl/5.12.3 /usr/lib64/perl5/vendor_perl/5.12.2 /usr/lib64/perl5/vendor_perl /usr/lib64/perl5/5.12.4/x86_64-linux /usr/lib64/perl5/5.12.4 /usr/local/lib/site_perl .) at /usr/bin/mythtv-status line 29.
BEGIN failed--compilation aborted at /usr/bin/mythtv-status line 29.

I am looking into this.

**Comment by MarcT** [comment]
This will need to be merged with all other branches that have mythtv-status in them. I'll do that once my systems are back up and running.

**Comment by MarcT** [comment]
all ebuilds updated
