### ISSUE TITLE
mythtv-status

### ISSUE THREAD

**Issue by drescherjm** [MarcT/mt-mythtv#18]
Should we move mythtv-status from category app-misc to category media-tv to match the version in portage?

http://gentoo-portage.com/media-tv/mythtv-status

**Comment by MarcT** [comment]
I'll leave that up to you. I'm working on getting the SVN mods added to mythtv packaging. I have a fully working ebuild on my own machine based on their ebuilds. Once I get my initial changes merged, I plan to push here, https://github.com/MarcT/packaging/tree/master/Gentoo
