### ISSUE TITLE
cannot emerge mythweb because of dev-perl/Math-Round on amd64

### ISSUE THREAD

**Issue by Miwer** [MarcT/mt-mythtv#3]
Hi, 

You have made mythweb depend on Math-Round - that's fine, but could you also add the ~amd64 keyword to the Math-Round ebuild, so it's possible to emerge on amd64?

**Comment by MarcT** [comment]
Done.

**Comment by Miwer** [comment]
fast response - thanks :)

**Comment by MarcT** [comment]
NP! I had just gotten inside form doing yardwork when your message came in. It was a quick enough change.
