### ISSUE TITLE
Install fails on Myth 25803 and up.

### ISSUE THREAD

**Issue by MarcT** [MarcT/mt-mythtv#5]
Since the breakaway of FFMPEG into its own “external” folder, the overlay fails on the install stage.
25803 to 25815 gives a sanbox error.
25816 and up gives the error : Aborting due to QA concerns: 54 files installed in /var/tmp/portage/media-tv/mythtv-9999/image///var/tmp/portage/media-tv/mythtv-9999/image/

**Comment by MarcT** [comment]
Fixed in r111

**Comment by Miwer** [comment]
Hi, I got that one too. Good work on fixing it.
Maybe you should create a ticket on mythtv.org (if you haven't allready), so they can fix it upstream?

**Comment by Miwer** [comment]
Hi, I got that one too. Good work on fixing it.
Maybe you should create a ticket on mythtv.org (if you haven't already), so they can fix it upstream?

**Comment by MarcT** [comment]
It doesnt seem to be a myth issue but a Gentoo one. John Drescher from the project is aware, as I asked him if he had seen it yet. He had not tried building since the change, but he was going to look into it. He also has been fiven the fix. In the meantime thats the fix for us.
