### ISSUE TITLE
emerge fails after mythtv r25900

### ISSUE THREAD

**Issue by Miwer** [MarcT/mt-mythtv#6]
After removing bindings/perl/perl.pro, emerge fails when trying to patch that file.
You need to remove the following lines from the mythtv ebuild:

```
    # Perl bits need to go into vender_perl and not site_perl
    sed -e "s:pure_install:pure_install INSTALLDIRS=vendor:" \
            -i "${S}"/bindings/perl/perl.pro
```

**Comment by MarcT** [comment]
Which version removed perl.pro? I havent seen this one yet and I am using perl bindings.

**Comment by MarcT** [comment]
Never mind, I found it. Its VERY recent.

**Comment by MarcT** [comment]
You sure we want to remove it and not change it to work on the new Makefile?

**Comment by Miwer** [comment]
Well no. Better not change it yet - I'm testing it now (it's building as I'm writing this), so I'll see what happens, and will write again afterwards.

**Comment by MarcT** [comment]
Ok, just tell me.
The original command changes
perl_install.commands = $(MAKE) -f Makefile.perl pure_install PERL_INSTALL_ROOT=\"$(INSTALL_ROOT)\" PREFIX=$${PREFIX}
to
perl_install.commands = $(MAKE) -f Makefile.perl pure_install INSTALLDIRS=vendor: PERL_INSTALL_ROOT=\"$(INSTALL_ROOT)\" PREFIX=$${PREFIX}

The new Makefile has a similar line
$(MAKE) -f Makefile.perl pure_install $(ROOT_FLAGS) PREFIX="$(PREFIX)"
I belive we would want to make the same change.

**Comment by Miwer** [comment]
Yup - I came to the same conclusion, after taking a closer look at it - I stopped my build, changed the ebuild (only changed the filename now), and it's building again. Will post back.

**Comment by Miwer** [comment]
Ok - looks like it is working... perl extensions are still installed in vendor_perl and not site_perl.
so the only thing needed would be changing the filename perl.pro into Makefile

**Comment by MarcT** [comment]
fixed in r112
