### ISSUE TITLE
0.23 branch and IUSE issues

### ISSUE THREAD

**Issue by Floppe** [MarcT/mt-mythtv#7]
FYI, mythtv and mythmusic have IUSE depend issues.

// Floppe

**Comment by MarcT** [comment]
I have never supported the 0.23-fixes branch. I had added drescherjm as a collaborator because he was using that branch but I think he is using the 0.24-fixes branch now.
If you want to submit the fixes I'll apply them.

**Comment by Floppe** [comment]
Thought I should submit but now I see they switched to GitHub also. So maybe I'll abandon 0.23-fixes and wait for your 0.24-fixes to use git :)

**Comment by MarcT** [comment]
0.24-fixes does use git.. I'm confused...

**Comment by MarcT** [comment]
OK, I see it now. I missed the announcement yesterday,
Ugh.. This will be fun.

**Comment by MarcT** [comment]
0.24 fixes is using git.feel free to identify any breakage.

**Comment by drescherjm** [comment]
I missed this discussion. I am still using 0.23-fixes for now although I plan to update soon. I believe I committed the fix of the IUSE on mythtv yesterday but I have not looked into mythmusic.

**Comment by Floppe** [comment]
0.24 fixes installed and working. Thanks. Also tested compile 0.23 fixes and it worked although I guess SVN will be dropped by mythtv.org soon.

**Comment by MarcT** [comment]
Actually, according to their own devs, it won't. It will however become read only.
0.23-fixes, at this point, should be old enough to not need to have its checkout changed. I don't see the devs continuing to update 0.23 when 0.24 is out. However, if this turns out to be wrong I'll port it over as well.
