### ISSUE TITLE
Sandbox violations in mythweather plugin

### ISSUE THREAD

**Issue by Miwer** [MarcT/mt-mythtv#8]
Hi, 
There seems to be multiple sandbox violations, when emerging mythweather. My guess would be, that the INSTDIR variable is set incorrectly, which causes the install phase to fail.

For example:

<pre>make -C ca_envcan install INSTDIR=/usr/share/mythtv/mythweather/scripts/ca_envcan
make[2]: Entering directory `/var/tmp/portage/media-plugins/mythweather-9999/work/mythweather/mythweather/mythweather/scripts/ca_envcan'
[ "envcan.pl envcan_animaps.pl" != "" ] && \
            /usr/bin/install -m 755 -d /usr/share/mythtv/mythweather/scripts/ca_envcan/ && \
            for i in envcan.pl envcan_animaps.pl ; do /usr/bin/install -m 755 $i /usr/share/mythtv/mythweather/scripts/ca_envcan/ ; done
ACCESS DENIED  unlink:       /usr/share/mythtv/mythweather/scripts/ca_envcan/envcan.pl
/usr/bin/install: cannot remove `/usr/share/mythtv/mythweather/scripts/ca_envcan/envcan.pl': Permission denied
</pre>

I'm trying to install trunk revision 27240.

**Comment by MarcT** [comment]
I was not seeing this on my machine.
I'm more worried about MythTV switching from svn to git at the moment. Since I am using 0.24-fixes myself that is the branch I am doing all my git testing on. Once I migrate those changes to to the main branch try it again.

**Comment by Miwer** [comment]
Ok - I'll look forward to it :)

**Comment by MarcT** [comment]
This is still in the git version. It is a problem with the Makefile in the scripts folder.

**Comment by Miwer** [comment]
Yeah I thought so... maybe it needs a patch like the sandbox patch for mythtv ebuild.

**Comment by MarcT** [comment]
Added a patch that should fix this. Please test and reply.
I have submitted the patch to the mythtv devs for their consideration.

**Comment by MarcT** [comment]
patch was denied citing it would be a reversal of the migration away from qmake which  caused issues.
Found another way to do this without switching back to qmake. This method is much simpler.
