### ISSUE TITLE
Error emerging mythweb

### ISSUE THREAD

**Issue by Miwer** [MarcT/mt-mythtv#9]
Hi,

I'm having problems emerging mythweb, see the error messages below - can anyone confirm this?

<pre>
>>> Emerging (1 of 1) www-apps/mythweb-9999 from MythTV-trunk
 * Package:    www-apps/mythweb-9999
 * Repository: MythTV-trunk
 * USE:  amd64 elibc_glibc kernel_linux multilib nls userland_GNU vhosts
 * 
 * Using dev-lang/php-5.3.3-r3
 * 
 * Checking for required PHP feature(s) ...
>>> Unpacking source...
mkdir: cannot create directory `/var/tmp/portage/www-apps/mythweb-9999/distdir/svn-src': Permission denied
 * ERROR: www-apps/mythweb-9999 failed:
 *   subversion: can't mkdir /var/tmp/portage/www-apps/mythweb-9999/distdir/svn-src.
 * 
 * Call stack:
 *     ebuild.sh, line   56:  Called src_unpack
 *   environment, line 3836:  Called myth-svn_src_unpack
 *   environment, line 2908:  Called subversion_src_unpack
 *   environment, line 4181:  Called subversion_fetch
 *   environment, line 4068:  Called die
 * The specific snippet of code:
 *           mkdir -p "${ESVN_STORE_DIR}" || die "${ESVN}: can't mkdir ${ESVN_STORE_DIR}.";

</pre>

**Comment by MarcT** [comment]
Once again, I never saw this on my machine. In the process of migrating the ebuilds to pull from git after the MythTV announcement the other day. Once that is done try this again.

**Comment by drescherjm** [comment]
The following is weird. 
mkdir: cannot create directory '/var/tmp/portage/www-apps/mythweb-9999/distdir/svn-src': Permission denied

I mean root not having permissions to create a folder. I would look at this folder and see what exactly is causing the problem.

**Comment by Miwer** [comment]
Oh my.. didn't see that coming, and I only saw the announcement after you told me :)

drescherjm:
yeah i find that wierd to - unless it's a sandbox issue, which I suspect it is.

Anyway I found the culprit - in mythweb-9999.ebuild line 11 is the following variable set:

<pre>
ESVN_STORE_DIR="${DISTDIR}/svn-src"
</pre>

... however, when comparing to the myth-svn.eclass (used by the other plugins), this line is commented out. I also commented out that line in the mythweb ebuild, and now it's working again here.

**Comment by MarcT** [comment]
This should be resolved in the new release. Test it out and reply.

**Comment by MarcT** [comment]
closing

**Comment by Miwer** [comment]
Thanks... tested and working :)
